name: Docker Image for PUFA computing Frontend

on:
   push:
      branches:
         - master
         - development

jobs:
   build_and_push:
      runs-on: ubuntu-latest
      steps:
         - uses: actions/checkout@v3
         - name: Build the Docker image
           run: |
              docker login -u kizoukun -p ${{ secrets.GH_TOKEN }} ghcr.io
              docker build . --tag ghcr.io/kizoukun/pufafrontend:latest
              docker push ghcr.io/kizoukun/pufafrontend:latest
